name = "resumehub"
compatibility_date = "2024-01-10"

[site]
bucket = "./"

[build]
command = ""

[functions]
directory = "functions"

[[kv_namespaces]]
binding = "CONTACTS"
id = ""  # Add your KV namespace ID here

# Optional: Configure environment variables
[vars]
ENVIRONMENT = "production"
